### ISSUE TITLE
xmlrpc.py package_releases() method results in 500 Internal Server Error

### ISSUE THREAD

**Issue by impracticably** [mardiros/pyshop#45]
Running this:

```python
import xmlrpclib
import pprint

client = xmlrpclib.ServerProxy('http://192.168.197.42:8000/pypi/')
# this works fine:
# pprint.pprint(client.list_packages())
# this doesn't:
pprint.pprint(client.package_releases('somepackage'))
```

...results in the following stack trace:

```
Traceback (most recent call last):
  File "/Users/some.user/PycharmProjects/testproject/xmlrpctest.py", line 8, in <module>
    pprint.pprint(client.package_releases('somepackage'))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1312, in single_request
    response.msg,
xmlrpclib.ProtocolError: <ProtocolError for 192.168.197.42:8000/pypi/: 500 Internal Server Error>
```

Meanwhile, over on the server, pyshop.log provides more information:

```
2014-12-11 23:05:22,980 ERROR [waitress][Dummy-2] Exception when serving /pypi/
Traceback (most recent call last):
  File "/home/some.user/pyshop/lib/python2.7/site-packages/waitress/channel.py", line 337, in service
    task.service()
  File "/home/some.user/pyshop/lib/python2.7/site-packages/waitress/task.py", line 173, in service
    self.execute()
  File "/home/some.user/pyshop/lib/python2.7/site-packages/waitress/task.py", line 392, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/home/some.user/pyshop/lib/python2.7/site-packages/pyramid/router.py", line 242, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/some.user/pyshop/lib/python2.7/site-packages/pyramid/router.py", line 217, in invoke_subrequest
    response = handle_request(request)
  File "/home/some.user/pyshop/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/some.user/pyshop/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 92, in tm_tween
    reraise(*exc_info)
  File "/home/some.user/pyshop/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 73, in tm_tween
    response = handler(request)
  File "/home/some.user/pyshop/lib/python2.7/site-packages/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/home/some.user/pyshop/lib/python2.7/site-packages/pyramid/config/views.py", line 385, in viewresult_to_response
    result = view(context, request)
  File "/home/some.user/pyshop/lib/python2.7/site-packages/pyramid/config/views.py", line 489, in _class_view
    response = inst()
  File "/home/some.user/pyshop/lib/python2.7/site-packages/pyramid_xmlrpc/__init__.py", line 119, in __call__
    return xmlrpc_response(getattr(self,method)(*params))
  File "/home/some.user/pyshop/lib/python2.7/site-packages/pyshop/views/xmlrpc.py", line 36, in package_releases
    releases = Release.by_package_name(session, package_name, show_hidden)
AttributeError: type object 'Release' has no attribute 'by_package_name'
```

Indeed, xmlrpc.py does call Release.by_package_name() at line 36:

```python
30    def package_releases(self, package_name, show_hidden=False):
31        """
32        Retrieve a list of the releases registered for the given package_name.
33        Returns a list with all version strings if show_hidden is True or
34        only the non-hidden ones otherwise."""
35        session = DBSession()
36        releases = Release.by_package_name(session, package_name, show_hidden)
37        session.rollback()
38        return releases
```

...but the Release class in models.py does not appear to define by_package_name() at all. Just saying, y'all might want to take a look. ;-)

Thanks!

**Comment by mardiros** [comment]
See
https://github.com/mardiros/pyshop/blob/master/pyshop/views/xmlrpc.py#L17

I was waiting that pull request https://github.com/Pylons/pyramid_xmlrpc/pull/2
to be reintegrated to get this working.

But now it is fixed in b0cae9e78b4e53458d6bc88cb70f1ffae979b870

The XML-RPC works (minimally)
