### ISSUE TITLE
Error pkg_resources.DistributionNotFound: waitress while starting

### ISSUE THREAD

**Issue by c4s4** [mardiros/pyshop#51]
I followed the installation procedure described on page https://pypi.python.org/pypi/pyshop with release 1.2.2. The server fails to start with following error in log file :

```
Traceback (most recent call last):
  File "/home/pyshop/pyshop/bin/pserve", line 9, in <module>
    load_entry_point('pyramid==1.5.3', 'console_scripts', 'pserve')()
  File "/home/pyshop/pyshop/lib/python2.6/site-packages/pyramid/scripts/pserve.py", line 58, in main
    return command.run()
  File "/home/pyshop/pyshop/lib/python2.6/site-packages/pyramid/scripts/pserve.py", line 325, in run
    relative_to=base, global_conf=vars)
  File "/home/pyshop/pyshop/lib/python2.6/site-packages/pyramid/scripts/pserve.py", line 367, in loadserver
    server_spec, name=name, relative_to=relative_to, **kw)
  File "/home/pyshop/pyshop/lib/python2.6/site-packages/paste/deploy/loadwsgi.py", line 255, in loadserver
    return loadobj(SERVER, uri, name=name, **kw)
  File "/home/pyshop/pyshop/lib/python2.6/site-packages/paste/deploy/loadwsgi.py", line 271, in loadobj
    global_conf=global_conf)
  File "/home/pyshop/pyshop/lib/python2.6/site-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext
    global_conf=global_conf)
  File "/home/pyshop/pyshop/lib/python2.6/site-packages/paste/deploy/loadwsgi.py", line 320, in _loadconfig
    return loader.get_context(object_type, name, global_conf)
  File "/home/pyshop/pyshop/lib/python2.6/site-packages/paste/deploy/loadwsgi.py", line 454, in get_context
    section)
  File "/home/pyshop/pyshop/lib/python2.6/site-packages/paste/deploy/loadwsgi.py", line 476, in _context_from_use
    object_type, name=use, global_conf=global_conf)
  File "/home/pyshop/pyshop/lib/python2.6/site-packages/paste/deploy/loadwsgi.py", line 406, in get_context
    global_conf=global_conf)
  File "/home/pyshop/pyshop/lib/python2.6/site-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext
    global_conf=global_conf)
  File "/home/pyshop/pyshop/lib/python2.6/site-packages/paste/deploy/loadwsgi.py", line 328, in _loadegg
    return loader.get_context(object_type, name, global_conf)
  File "/home/pyshop/pyshop/lib/python2.6/site-packages/paste/deploy/loadwsgi.py", line 620, in get_context
    object_type, name=name)
  File "/home/pyshop/pyshop/lib/python2.6/site-packages/paste/deploy/loadwsgi.py", line 640, in find_egg_entry_point
    pkg_resources.require(self.spec)
  File "/home/pyshop/pyshop/lib/python2.6/site-packages/distribute-0.6.10-py2.6.egg/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/pyshop/pyshop/lib/python2.6/site-packages/distribute-0.6.10-py2.6.egg/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: waitress
Removing PID file pyramid.pid
```

**Comment by mardiros** [comment]
There is an error in the install process

pip install "pyshop[waitress]"

instead of

pip install pyshop[waitress]

I suppose you do 

pip install pyshop


did you ?

**Comment by mardiros** [comment]
I fix the README both on pypi and github

**Comment by c4s4** [comment]
This doesn't fix the problem. I have the exact same stack trace installing with:

    pip install "pyshop[waitress]"

**Comment by mardiros** [comment]
I have tested before and it works for me,
even on a python 2.6

I suppose your version of pip is very old, and does not handle
the extra requirements correctly.

See https://pip.pypa.io/en/latest/news.html

    1.1 (2012-02-16)
    Fixed #7 - Pip now supports optionally installing setuptools “extras” dependencies; e.g. “pip install Paste[openid]”. Thanks Matt Maker and Olivier Girardot.

**Comment by mardiros** [comment]
Just do

    pip install waitress

**Comment by c4s4** [comment]
I think that this is an issue with my PIP installation (on an old Python 2.6.6) because I have had the same issue installting another package.

Sorry for the trouble

**Comment by powellchristoph** [comment]
Why isn't waitress included as a requirement in the setup.py so it is automatically installed?

**Comment by mardiros** [comment]
Because you don't need waitress, you need a WSGI server.

And, for Pyramid, it's simpler if the server support paste format.

So you can use gunicorn or uwsgi instead of waitress if are more
familiar with them. that's not a problem.

And this is true for every wsgi application.
