### ISSUE TITLE
Package purge fails with postgresql backend

### ISSUE THREAD

**Issue by powellchristoph** [mardiros/pyshop#52]
I implemented the purge functionality before and it works well with SQLite, but blows up with Postgres and I am assuming MySQL. I know what the problem is and I would love to fix it myself, but my database knowledge isn't strong enough.

Any help would be greatly appreciated!

```
2015-03-26 16:08:18,491 INFO  [pyshop.security][Dummy-4] [72.3.234.177] GET http://wheel.cldbckp.com/prev/
2015-03-26 16:08:18,498 INFO  [pyshop.views.base][Dummy-4] dispatch view Index
2015-03-26 16:08:18,568 INFO  [pyshop.security][Dummy-1] [72.3.234.177] GET http://wheel.cldbckp.com/prev/pyshop/package
2015-03-26 16:08:18,575 INFO  [pyshop.views.base][Dummy-1] dispatch view List
2015-03-26 16:08:20,507 INFO  [pyshop.security][Dummy-2] [72.3.234.177] GET http://wheel.cldbckp.com/prev/pyshop/purge/package/156
2015-03-26 16:08:20,515 INFO  [pyshop.views.base][Dummy-2] dispatch view Purge
2015-03-26 16:08:23,782 INFO  [pyshop.security][Dummy-3] [72.3.234.177] GET http://wheel.cldbckp.com/prev/pyshop/purge/package/156?form.submitted=
2015-03-26 16:08:23,790 INFO  [pyshop.views.base][Dummy-3] dispatch view Purge
2015-03-26 16:08:33,698 ERROR [pyshop.views.base][Dummy-3] Error on view Purge
Traceback (most recent call last):
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/pyshop/views/base.py", line 48, in __call__
    self.session.flush()
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1919, in flush
    self._flush(objects)
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2037, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2001, in _flush
    flush_context.execute()
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 367, in execute
    n.execute_aggregate(self, set_)
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 644, in execute_aggregate
    uow)
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 117, in delete_obj
    cached_connections, mapper, table, delete)
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 694, in _emit_delete_statements
    c = connection.execute(statement, del_objects)
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 321, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1160, in _handle_dbapi_exception
    exc_info
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 928, in _execute_context
    context)
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 433, in do_executemany
    cursor.executemany(statement, parameters)
IntegrityError: (IntegrityError) update or delete on table "classifier" violates foreign key constraint "classifier__release_classifier_id_fkey" on table "classifier__release"
DETAIL:  Key (id)=(4) is still referenced from table "classifier__release".
 'DELETE FROM classifier WHERE classifier.id = %(id)s' ({'id': 4}, {'id': 5}, {'id': 11}, {'id': 14}, {'id': 15}, {'id': 48}, {'id': 58}, {'id': 178})
2015-03-26 16:08:33,699 ERROR [waitress][Dummy-3] Exception when serving /prev/pyshop/purge/package/156
Traceback (most recent call last):
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/waitress/channel.py", line 337, in service
    task.service()
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/waitress/task.py", line 173, in service
    self.execute()
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/waitress/task.py", line 392, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/pyramid/router.py", line 242, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/pyramid/router.py", line 217, in invoke_subrequest
    response = handle_request(request)
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 82, in tm_tween
    reraise(*exc_info)
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 63, in tm_tween
    response = handler(request)
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/pyramid/config/views.py", line 245, in _secured_view
    return view(context, request)
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/pyramid/config/views.py", line 355, in rendered_view
    result = view(context, request)
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/pyramid/config/views.py", line 475, in _class_requestonly_view
    response = inst()
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/pyshop/views/base.py", line 48, in __call__
    self.session.flush()
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1919, in flush
    self._flush(objects)
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2037, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2001, in _flush
    flush_context.execute()
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 367, in execute
    n.execute_aggregate(self, set_)
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 644, in execute_aggregate
    uow)
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 117, in delete_obj
    cached_connections, mapper, table, delete)
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 694, in _emit_delete_statements
    c = connection.execute(statement, del_objects)
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 321, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1160, in _handle_dbapi_exception
    exc_info
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 928, in _execute_context
    context)
  File "/opt/pyshop/preview/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 433, in do_executemany
    cursor.executemany(statement, parameters)
IntegrityError: (IntegrityError) update or delete on table "classifier" violates foreign key constraint "classifier__release_classifier_id_fkey" on table "classifier__release"
DETAIL:  Key (id)=(4) is still referenced from table "classifier__release".
 'DELETE FROM classifier WHERE classifier.id = %(id)s' ({'id': 4}, {'id': 5}, {'id': 11}, {'id': 14}, {'id': 15}, {'id': 48}, {'id': 58}, {'id': 178})
```

**Comment by powellchristoph** [comment]
@mardiros Any thoughts on this?
