### ISSUE TITLE
Upload failed (500): Internal Server Error

### ISSUE THREAD

**Issue by kumy** [mardiros/pyshop#60]
Hi,

I tried to use pyshop here, when uploading my first package I get `Upload failed (500): Internal Server Error`

pyshop (1.2.2)

What's wrong? :)

```
2015-06-18 16:59:28,570 ERROR [waitress][Dummy-2] Exception when serving /simple/ 
Traceback (most recent call last): 
  File "/opt/hosting/run/pyshop/local/lib/python2.7/site-packages/waitress/channel.py", line 337, in service 
    task.service() 
  File "/opt/hosting/run/pyshop/local/lib/python2.7/site-packages/waitress/task.py", line 173, in service 
    self.execute() 
  File "/opt/hosting/run/pyshop/local/lib/python2.7/site-packages/waitress/task.py", line 392, in execute 
    app_iter = self.channel.server.application(env, start_response) 
  File "/opt/hosting/run/pyshop/local/lib/python2.7/site-packages/pyramid/router.py", line 223, in __call__ 
    response = self.invoke_subrequest(request, use_tweens=True) 
  File "/opt/hosting/run/pyshop/local/lib/python2.7/site-packages/pyramid/router.py", line 198, in invoke_subrequest 
    response = handle_request(request) 
  File "/opt/hosting/run/pyshop/local/lib/python2.7/site-packages/pyramid/tweens.py", line 20, in excview_tween 
    response = handler(request) 
  File "/opt/hosting/run/pyshop/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 99, in tm_tween 
    reraise(*exc_info) 
  File "/opt/hosting/run/pyshop/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 80, in tm_tween 
    response = handler(request) 
  File "/opt/hosting/run/pyshop/local/lib/python2.7/site-packages/pyramid/router.py", line 145, in handle_request 
    view_name 
  File "/opt/hosting/run/pyshop/local/lib/python2.7/site-packages/pyramid/view.py", line 527, in _call_view 
    response = view_callable(context, request) 
  File "/opt/hosting/run/pyshop/local/lib/python2.7/site-packages/pyramid/config/views.py", line 243, in _secured_view 
    return view(context, request) 
  File "/opt/hosting/run/pyshop/local/lib/python2.7/site-packages/pyramid/config/views.py", line 352, in rendered_view 
    result = view(context, request) 
  File "/opt/hosting/run/pyshop/local/lib/python2.7/site-packages/pyramid/config/views.py", line 480, in _class_requestonly_view 
    response = inst() 
  File "/opt/hosting/run/pyshop/local/lib/python2.7/site-packages/pyshop/views/base.py", line 44, in __call__ 
    response = self.render() 
  File "/opt/hosting/run/pyshop/local/lib/python2.7/site-packages/pyshop/views/simple.py", line 144, in render 
    create_if_not_exists=True) 
  File "/opt/hosting/run/pyshop/local/lib/python2.7/site-packages/pyshop/models.py", line 427, in by_name 
    classifier = cls.first(session, where=(cls.name == name,)) 
  File "/opt/hosting/run/pyshop/local/lib/python2.7/site-packages/pyshop/helpers/sqla.py", line 52, in first 
    return cls.build_query(session, join, where, order_by).first() 
  File "/opt/hosting/run/pyshop/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2444, in first 
    ret = list(self[0:1]) 
  File "/opt/hosting/run/pyshop/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2280, in __getitem__ 
    return list(res) 
  File "/opt/hosting/run/pyshop/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2515, in __iter__ 
    return self._execute_and_instances(context) 
  File "/opt/hosting/run/pyshop/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2530, in _execute_and_instances 
    result = conn.execute(querycontext.statement, self._params) 
  File "/opt/hosting/run/pyshop/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute 
    return meth(self, multiparams, params) 
  File "/opt/hosting/run/pyshop/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection 
    return connection._execute_clauseelement(self, multiparams, params) 
  File "/opt/hosting/run/pyshop/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement 
    compiled_sql, distilled_params 
  File "/opt/hosting/run/pyshop/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context 
    context) 
  File "/opt/hosting/run/pyshop/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception 
    exc_info 
  File "/opt/hosting/run/pyshop/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause 
    reraise(type(exception), exception, tb=exc_tb) 
  File "/opt/hosting/run/pyshop/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context 
    context) 
  File "/opt/hosting/run/pyshop/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute 
    cursor.execute(statement, parameters) 
InterfaceError: (sqlite3.InterfaceError) Error binding parameter 0 - probably unsupported type. [SQL: u'SELECT classifier.id AS classifier_id, classifier.created_at AS classifier_created_at, classifier.name AS classifier_name, classifier.parent_id AS classifier_parent_id, classifier.category AS classifier_category \nFROM classifier \nWHERE classifier.name = ?\n LIMIT ? OFFSET ?'] [parameters: (FieldStorage('classifiers', u'Development Status :: 5 - Production/Stable'), 1, 0)] 
```

**Comment by mardiros** [comment]
Which version of SQLAlchemy are you using ?

**Comment by kumy** [comment]
SQLAlchemy (1.0.5)

```
$ pip list
argparse (1.2.1)
cryptacular (1.4.1)
docutils (0.12)
Jinja2 (2.7.3)
MarkupSafe (0.23)
PasteDeploy (1.5.2)
pbkdf2 (1.3)
pyramid (1.6a1)
pyramid-filterwarnings (0.4)
pyramid-jinja2 (2.5)
pyramid-tm (0.12)
pyramid-xmlrpc (0.1)
pyshop (1.2.2)
repoze.lru (0.6)
requests (2.7.0)
SQLAlchemy (1.0.5)
transaction (1.4.4)
translationstring (1.3)
venusian (1.0)
waitress (0.8.9)
WebOb (1.4.1)
wsgiref (0.1.2)
zope.deprecation (4.1.2)
zope.interface (4.1.2)
zope.sqlalchemy (0.7.6)
```
