### ISSUE TITLE
Error When Attempting to Download Requests package

### ISSUE THREAD

**Issue by beegmon** [mardiros/pyshop#85]
Hello,
I have a fresh install of pyshop and up until today everything seemed to be in order. However, I am getting an error when attempting to pip install requests. It seems that is attempts to catch every version of the the requests package, and then fails when it tries to serve it to the client. I didn't include the entire log entry because its very long as it lists every version of request that it attempt to mirror. I only included the last version it attempt to mirror before serving the request.

The package is also never written to disk. I don't see a r/requests directory/package on disk after the failure.

Any help would be greatly appreciated!

```
.....
Aug 21 23:01:32 sd-repo-001 python[15578]: 2017-08-21 23:01:32,973 INFO  [pyshop.views.simple][waitress] Mirroring version 2.17.3
Aug 21 23:01:33 sd-repo-001 python[15578]: 2017-08-21 23:01:33,519 INFO  [pyshop.views.simple][waitress] Create release 2.17.3 for package requests
Aug 21 23:01:33 sd-repo-001 python[15578]: 2017-08-21 23:01:33,520 INFO  [pyshop.views.simple][waitress] Looking for author Kenneth Reitz
Aug 21 23:01:34 sd-repo-001 python[15578]: 2017-08-21 23:01:34,174 INFO  [pyshop.views.simple][waitress] package requests mirrored
Aug 21 23:01:34 sd-repo-001 python[15578]: 2017-08-21 23:01:34,789 INFO  [pyshop.security][waitress] [127.0.0.1] GET http://localhost:8000/pyshop/package
Aug 21 23:01:34 sd-repo-001 python[15578]: 2017-08-21 23:01:34,790 INFO  [pyshop.views.base][waitress] dispatch view Login
Aug 21 23:01:35 sd-repo-001 python[15578]: 2017-08-21 23:01:35,200 ERROR [waitress][waitress] Exception when serving /simple/requests/
Aug 21 23:01:35 sd-repo-001 python[15578]: Traceback (most recent call last):
Aug 21 23:01:35 sd-repo-001 python[15578]: File "/opt/pyshop/lib64/python3.6/site-packages/pyramid/tweens.py", line 12, in _error_handler
Aug 21 23:01:35 sd-repo-001 python[15578]: response = request.invoke_exception_view(exc_info)
Aug 21 23:01:35 sd-repo-001 python[15578]: File "/opt/pyshop/lib64/python3.6/site-packages/pyramid/view.py", line 756, in invoke_exception_view
Aug 21 23:01:35 sd-repo-001 python[15578]: raise HTTPNotFound
Aug 21 23:01:35 sd-repo-001 python[15578]: pyramid.httpexceptions.HTTPNotFound: The resource could not be found.
Aug 21 23:01:35 sd-repo-001 python[15578]: During handling of the above exception, another exception occurred:
Aug 21 23:01:35 sd-repo-001 python[15578]: Traceback (most recent call last):
Aug 21 23:01:35 sd-repo-001 python[15578]: File "/opt/pyshop/lib64/python3.6/site-packages/waitress/channel.py", line 338, in service
Aug 21 23:01:35 sd-repo-001 python[15578]: task.service()
Aug 21 23:01:35 sd-repo-001.saildrone.com python[15578]: File "/opt/pyshop/lib64/python3.6/site-packages/waitress/task.py", line 169, in service
Aug 21 23:01:35 sd-repo-001 python[15578]: self.execute()
Aug 21 23:01:35 sd-repo-001 python[15578]: File "/opt/pyshop/lib64/python3.6/site-packages/waitress/task.py", line 399, in execute
Aug 21 23:01:35 sd-repo-001 python[15578]: app_iter = self.channel.server.application(env, start_response)
Aug 21 23:01:35 sd-repo-001 python[15578]: File "/opt/pyshop/lib64/python3.6/site-packages/pyramid/router.py", line 270, in __call__
Aug 21 23:01:35 sd-repo-001 python[15578]: response = self.execution_policy(environ, self)
Aug 21 23:01:35 sd-repo-001 python[15578]: File "/opt/pyshop/lib64/python3.6/site-packages/pyramid/router.py", line 278, in default_execution_policy
Aug 21 23:01:35 sd-repo-001 python[15578]: return request.invoke_exception_view(reraise=True)
Aug 21 23:01:35 sd-repo-001 python[15578]: File "/opt/pyshop/lib64/python3.6/site-packages/pyramid/view.py", line 755, in invoke_exception_view
Aug 21 23:01:35 sd-repo-001 python[15578]: reraise_(*exc_info)
Aug 21 23:01:35 sd-repo-001.saildrone.com python[15578]: File "/opt/pyshop/lib64/python3.6/site-packages/pyramid/compat.py", line 148, in reraise
Aug 21 23:01:35 sd-repo-001 python[15578]: raise value
Aug 21 23:01:35 sd-repo-001 python[15578]: File "/opt/pyshop/lib64/python3.6/site-packages/pyramid/router.py", line 276, in default_execution_policy
Aug 21 23:01:35 sd-repo-001 python[15578]: return router.invoke_request(request)
Aug 21 23:01:35 sd-repo-001.saildrone.com python[15578]: File "/opt/pyshop/lib64/python3.6/site-packages/pyramid/router.py", line 249, in invoke_request
Aug 21 23:01:35 sd-repo-001. python[15578]: response = handle_request(request)
Aug 21 23:01:35 sd-repo-001 python[15578]: File "/opt/pyshop/lib64/python3.6/site-packages/pyramid_tm/__init__.py", line 171, in tm_tween
Aug 21 23:01:35 sd-repo-001. python[15578]: reraise(*exc_info)
Aug 21 23:01:35 sd-repo-001 python[15578]: File "/opt/pyshop/lib64/python3.6/site-packages/pyramid_tm/compat.py", line 36, in reraise
Aug 21 23:01:35 sd-repo-001 python[15578]: raise value
Aug 21 23:01:35 sd-repo-001 python[15578]: File "/opt/pyshop/lib64/python3.6/site-packages/pyramid_tm/__init__.py", line 136, in tm_tween
Aug 21 23:01:35 sd-repo-001 python[15578]: response = handler(request)
Aug 21 23:01:35 sd-repo-001 python[15578]: File "/opt/pyshop/lib64/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
Aug 21 23:01:35 sd-repo-001 python[15578]: response = _error_handler(request, exc)
Aug 21 23:01:35 sd-repo-001 python[15578]: File "/opt/pyshop/lib64/python3.6/site-packages/pyramid/tweens.py", line 16, in _error_handler
Aug 21 23:01:35 sd-repo-001 python[15578]: reraise(*exc_info)
Aug 21 23:01:35 sd-repo-001 python[15578]: File "/opt/pyshop/lib64/python3.6/site-packages/pyramid/compat.py", line 148, in reraise
Aug 21 23:01:35 sd-repo-001 python[15578]: raise value
Aug 21 23:01:35 sd-repo-001 python[15578]: File "/opt/pyshop/lib64/python3.6/site-packages/pyramid/tweens.py", line 39, in excview_tween
Aug 21 23:01:35 sd-repo-001 python[15578]: response = handler(request)
Aug 21 23:01:35 sd-repo-001 python[15578]: File "/opt/pyshop/lib64/python3.6/site-packages/pyramid/router.py", line 156, in handle_request
Aug 21 23:01:35 sd-repo-001 python[15578]: view_name
Aug 21 23:01:35 sd-repo-001. python[15578]: File "/opt/pyshop/lib64/python3.6/site-packages/pyramid/view.py", line 642, in _call_view
Aug 21 23:01:35 sd-repo-001 python[15578]: response = view_callable(context, request)
Aug 21 23:01:35 sd-repo-001 python[15578]: File "/opt/pyshop/lib64/python3.6/site-packages/pyramid/viewderivers.py", line 301, in secured_view
Aug 21 23:01:35 sd-repo-001 python[15578]: return view(context, request)
Aug 21 23:01:35 sd-repo-001 python[15578]: File "/opt/pyshop/lib64/python3.6/site-packages/pyramid/viewderivers.py", line 462, in rendered_view
Aug 21 23:01:35 sd-repo-001 python[15578]: request, result, view_inst, context)
Aug 21 23:01:35 sd-repo-001 python[15578]: File "/opt/pyshop/lib64/python3.6/site-packages/pyramid/renderers.py", line 435, in render_view
Aug 21 23:01:35 sd-repo-001 python[15578]: return self.render_to_response(response, system, request=request)
Aug 21 23:01:35 sd-repo-001 python[15578]: File "/opt/pyshop/lib64/python3.6/site-packages/pyramid/renderers.py", line 458, in render_to_response
Aug 21 23:01:35 sd-repo-001 python[15578]: result = self.render(value, system_values, request=request)
Aug 21 23:01:35 sd-repo-001 python[15578]: File "/opt/pyshop/lib64/python3.6/site-packages/pyramid/renderers.py", line 454, in render
Aug 21 23:01:35 sd-repo-001 python[15578]: result = renderer(value, system_values)
Aug 21 23:01:35 sd-repo-001 python[15578]: File "/opt/pyshop/lib64/python3.6/site-packages/pyramid_jinja2/__init__.py", line 265, in __call__
Aug 21 23:01:35 sd-repo-001 python[15578]: return template.render(system)
Aug 21 23:01:35 sd-repo-001 python[15578]: File "/opt/pyshop/lib64/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
Aug 21 23:01:35 sd-repo-001 python[15578]: return original_render(self, *args, **kwargs)
Aug 21 23:01:35 sd-repo-001. python[15578]: File "/opt/pyshop/lib64/python3.6/site-packages/jinja2/environment.py", line 1008, in render
Aug 21 23:01:35 sd-repo-001 python[15578]: return self.environment.handle_exception(exc_info, True)
Aug 21 23:01:35 sd-repo-001 python[15578]: File "/opt/pyshop/lib64/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
Aug 21 23:01:35 sd-repo-001 python[15578]: reraise(exc_type, exc_value, tb)
Aug 21 23:01:35 sd-repo-001 python[15578]: File "/opt/pyshop/lib64/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
Aug 21 23:01:35 sd-repo-001 python[15578]: raise value.with_traceback(tb)
Aug 21 23:01:35 sd-repo-001 python[15578]: File "/opt/pyshop/lib64/python3.6/site-packages/pyshop/templates/pyshop/simple/show.html", line 2, in top-level template code
Aug 21 23:01:35 sd-repo-001 python[15578]: {% for r in package.sorted_releases %}
Aug 21 23:01:35 sd-repo-001 python[15578]: File "/opt/pyshop/lib64/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
Aug 21 23:01:35 sd-repo-001 python[15578]: return getattr(obj, attribute)
Aug 21 23:01:35 sd-repo-001 python[15578]: File "/opt/pyshop/lib64/python3.6/site-packages/pyshop/models.py", line 518, in sorted_releases
Aug 21 23:01:35 sd-repo-001 python[15578]: releases.sort(reverse=True)
Aug 21 23:01:35 sd-repo-001 python[15578]: TypeError: '<' not supported between instances of 'Release' and 'Release'

**Comment by beegmon** [comment]
I fixed the issue.

Turns out I was being dumb/to crafty. On my pip server I mount two dirs pyshop_data and pyshop_packages using FUSE from a dedicated pip_repo S3 bucket. I generally have had great luck mounting SQLite DBs using this method, but not in this case. Most of my sqlite DBs have very little if any read/write concurrency...

I moved my pyshop_data (where the sqlite DB is stored) to local disk and kept the pyshop_packages dir mounted from S3. This resolved the issue, and there are no more errors. 

What tipped me off was that SQL alchemy said the table was locked so it couldn't update it. it would be nice if pyshop added a timeout for these calls as I am sure if it waited a second or two for the lock to release it would be fine (it might do this already I haven't looked at the code). 

This is also probably why pyshop didn't save the request package when it said it was mirroring it. 

It's odd that i have only seen it with the requests package so far, but I am wondering if requests just has a ton of dependancies and while pyshop is trying to pull those in and update the DB the FUSE mount (S3 is eventually consistent) doesn't respond fast enough and it hits a lock. I should have known better, but the idea of putting everything in an S3 bucket that I could just mount and recover is my repo node fails got the best of me.

Any ways problem solved, I will go ahead and close this issue and backup the DB in another way.
