### ISSUE TITLE
Error in exception  when serving `/simple/requests/`

### ISSUE THREAD

**Issue by jethroguce** [mardiros/pyshop#94]
```
2019-03-18 07:23:30,616 INFO  [pyshop.views.simple][waitress] Create release 1.0.0 for package requests
2019-03-18 07:23:30,617 INFO  [pyshop.views.simple][waitress] Looking for author Kenneth Reitz
2019-03-18 07:23:31,225 INFO  [pyshop.views.simple][waitress] Mirroring version 2.12.0
2019-03-18 07:23:31,501 INFO  [pyshop.views.simple][waitress] Create release 2.12.0 for package requests
2019-03-18 07:23:31,502 INFO  [pyshop.views.simple][waitress] Looking for author Kenneth Reitz
2019-03-18 07:23:32,938 INFO  [pyshop.views.simple][waitress] Mirroring version 2.18.0
2019-03-18 07:23:34,161 INFO  [pyshop.views.simple][waitress] Create release 2.18.0 for package requests
2019-03-18 07:23:34,161 INFO  [pyshop.views.simple][waitress] Looking for author Kenneth Reitz
2019-03-18 07:23:35,537 INFO  [pyshop.views.simple][waitress] Mirroring version 2.4.3
2019-03-18 07:23:36,531 INFO  [pyshop.views.simple][waitress] Create release 2.4.3 for package requests
2019-03-18 07:23:36,532 INFO  [pyshop.views.simple][waitress] Looking for author Kenneth Reitz
2019-03-18 07:23:37,823 INFO  [pyshop.views.simple][waitress] Mirroring version 1.0.1
2019-03-18 07:23:38,826 INFO  [pyshop.views.simple][waitress] Create release 1.0.1 for package requests
2019-03-18 07:23:38,827 INFO  [pyshop.views.simple][waitress] Looking for author Kenneth Reitz
2019-03-18 07:23:40,173 INFO  [pyshop.views.simple][waitress] Mirroring version 2.0.1
2019-03-18 07:23:41,190 INFO  [pyshop.views.simple][waitress] Create release 2.0.1 for package requests
2019-03-18 07:23:41,191 INFO  [pyshop.views.simple][waitress] Looking for author Kenneth Reitz
2019-03-18 07:23:42,498 INFO  [pyshop.views.simple][waitress] package requests mirrored
2019-03-18 07:23:42,532 ERROR [waitress][waitress] Exception when serving /simple/requests/
Traceback (most recent call last):
  File "/media/swapdrive/local_pypi/env/lib/python3.4/site-packages/pyramid/tweens.py", line 13, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "/media/swapdrive/local_pypi/env/lib/python3.4/site-packages/pyramid/view.py", line 769, in invoke_exception_view
    raise HTTPNotFound
pyramid.httpexceptions.HTTPNotFound: The resource could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/swapdrive/local_pypi/env/lib/python3.4/site-packages/waitress/channel.py", line 336, in service
    task.service()
  File "/media/swapdrive/local_pypi/env/lib/python3.4/site-packages/waitress/task.py", line 175, in service
    self.execute()
  File "/media/swapdrive/local_pypi/env/lib/python3.4/site-packages/waitress/task.py", line 452, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/media/swapdrive/local_pypi/env/lib/python3.4/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/media/swapdrive/local_pypi/env/lib/python3.4/site-packages/pyramid/router.py", line 279, in default_execution_policy
    return request.invoke_exception_view(reraise=True)
  File "/media/swapdrive/local_pypi/env/lib/python3.4/site-packages/pyramid/view.py", line 768, in invoke_exception_view
    reraise_(*exc_info)
  File "/media/swapdrive/local_pypi/env/lib/python3.4/site-packages/pyramid/compat.py", line 179, in reraise
    raise value
  File "/media/swapdrive/local_pypi/env/lib/python3.4/site-packages/pyramid/router.py", line 277, in default_execution_policy
    return router.invoke_request(request)
  File "/media/swapdrive/local_pypi/env/lib/python3.4/site-packages/pyramid/router.py", line 249, in invoke_request
    response = handle_request(request)
  File "/media/swapdrive/local_pypi/env/lib/python3.4/site-packages/pyramid_tm/__init__.py", line 171, in tm_tween
    reraise(*exc_info)
  File "/media/swapdrive/local_pypi/env/lib/python3.4/site-packages/pyramid_tm/compat.py", line 36, in reraise
    raise value
File "/media/swapdrive/local_pypi/env/lib/python3.4/site-packages/pyramid_tm/__init__.py", line 136, in tm_tween
    response = handler(request)
  File "/media/swapdrive/local_pypi/env/lib/python3.4/site-packages/pyramid/tweens.py", line 43, in excview_tween
    response = _error_handler(request, exc)
  File "/media/swapdrive/local_pypi/env/lib/python3.4/site-packages/pyramid/tweens.py", line 17, in _error_handler
    reraise(*exc_info)
  File "/media/swapdrive/local_pypi/env/lib/python3.4/site-packages/pyramid/compat.py", line 179, in reraise
    raise value
  File "/media/swapdrive/local_pypi/env/lib/python3.4/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/media/swapdrive/local_pypi/env/lib/python3.4/site-packages/pyramid/router.py", line 148, in handle_request
    registry, request, context, context_iface, view_name
  File "/media/swapdrive/local_pypi/env/lib/python3.4/site-packages/pyramid/view.py", line 657, in _call_view
    response = view_callable(context, request)
  File "/media/swapdrive/local_pypi/env/lib/python3.4/site-packages/pyramid/viewderivers.py", line 325, in secured_view
    return view(context, request)
  File "/media/swapdrive/local_pypi/env/lib/python3.4/site-packages/pyramid/viewderivers.py", line 460, in rendered_view
    request, result, view_inst, context
  File "/media/swapdrive/local_pypi/env/lib/python3.4/site-packages/pyramid/renderers.py", line 451, in render_view
    return self.render_to_response(response, system, request=request)
  File "/media/swapdrive/local_pypi/env/lib/python3.4/site-packages/pyramid/renderers.py", line 474, in render_to_response
    result = self.render(value, system_values, request=request)
  File "/media/swapdrive/local_pypi/env/lib/python3.4/site-packages/pyramid/renderers.py", line 470, in render
    result = renderer(value, system_values)
  File "/media/swapdrive/local_pypi/env/lib/python3.4/site-packages/pyramid_jinja2/__init__.py", line 265, in __call__
    return template.render(system)
  File "/media/swapdrive/local_pypi/env/lib/python3.4/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/media/swapdrive/local_pypi/env/lib/python3.4/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/media/swapdrive/local_pypi/env/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/media/swapdrive/local_pypi/env/lib/python3.4/site-packages/pyshop/templates/pyshop/simple/show.html", line 2, in top-level template code
    {% for r in package.sorted_releases %}
  File "/media/swapdrive/local_pypi/env/lib/python3.4/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
  File "/media/swapdrive/local_pypi/env/lib/python3.4/site-packages/pyshop/models.py", line 518, in sorted_releases
    releases.sort(reverse=True)
TypeError: unorderable types: Release() < Release()
```

I am trying to install the `requests` package via the pyshop, but I am having the above error,

**Comment by jethroguce** [comment]
https://github.com/mardiros/pyshop/blob/b42510b9c3fa16e0e5710457401ac38fea5bf7a0/pyshop/models.py#L518

temporarily fixed my local, I added a `try/except`,
